from fastapi import FastAPI, Request
import random
import string

app = FastAPI()

# --- Middleware ---
# There are 2 ways to add middleware in FastAPI:
# 1. Using the @app.middleware decorator
@app.middleware("http")
async def request_id_logging(request: Request, call_next):
    '''
    A function call_next that will receive the request as a parameter, this function will pass the request to the corresponding path operation. Then it returns the response generated by the corresponding path operation.'''

    response = await call_next(request)
    random_letters = ''.join(random.choice(string.ascii_letters) for _ in range(10))
    print(f'Log {random_letters}')
    response.headers["X-request-ID"] = random_letters
    return response
    

# --- API Endpoints ---

# --- GET Request Methods ---
@app.get("/")
async def say_hi():
    return 'Hi there! Welcome to FastAPI with Middleware example.'

